<?php

namespace NetMedia\NetMadiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Cherche le media donnee en parametre.
 * Retourne false s'il ne trouve rien.
 * 
 *  @author optimus prime <laurent.brau@gmail.com>
 *  @return valeur mixe entre boolean et objet dql.
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    
    public function checkTwinMediaTitle($sMediaTitle) {
        
    //    echo "<br> dans le repo : ".$sMediaTitle."<br>";  
        $oReq = $this->createQueryBuilder('m');
        $oReq->where('m.titre = :titre')
                ->setParameter('titre', $sMediaTitle)
                ->getQuery()
                ->getResult()
                ;
        
                //var_dump($oReq);
        if ("" == $oReq) {
            $mReturnValue = false;
        }
        else {
             
            $mReturnValue = $oReq;
        }
        //var_dump($mReturnValue[0]->getTitre());die;
        return $mReturnValue;
    }
}
