<?php

namespace NetMedia\NetMadiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProducteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducteurRepository extends EntityRepository
{
}
