<?php

namespace NetMedia\NetMadiaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfilAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilAdminRepository extends EntityRepository
{
}
