parameters:
#    net_media.example.class: NetMedia\NetMadiaBundle\Example

services:
#    net_media.example:
#        class: %net_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
